## Demonstrate PyTorch

In [2]:
import torch

In [5]:
def times_five(number):
    return number * 5

In [6]:
x = 5
print(times_five(x))

25


In [7]:
# pass a Python object into this tensor constructor. Also had to make it an array there.
#  everything that you're going to be passing around in PyTorch is going to be an array or nested array of some sort.
x = torch.Tensor([x])
print(times_five(x))

tensor([25.])


In [8]:
x = torch.Tensor([x,x])
print(times_five(x))


tensor([25., 25.])


The main thing that PyTorch does is auto computes gradients. Functions with respects to variables.

In [14]:
x = 5
# Different method to actually generate a tensor for us instead of taking that value.
x = torch.randn(1, requires_grad=True)
#grad function. So that's why it's keeping track of what's happened to these variables underneath.
y = times_five(x) #compute the gradient. So we're essentially going to try to compute ey/ex.
y.backward() #backpropagation -- the derivative of Y with respect to x
print(x.grad) #print the gradient
print(x,y)


tensor([5.])
tensor([-0.0200], requires_grad=True) tensor([-0.1000], grad_fn=<MulBackward0>)


In [15]:
x = 5
# Different method to actually generate a tensor for us instead of taking that value.
x = torch.randn(1, requires_grad=True)
#grad function. So that's why it's keeping track of what's happened to these variables underneath.
y = times_five(x) * 4#compute the gradient. So we're essentially going to try to compute ey/ex.
y.backward() #backpropagation -- the derivative of Y with respect to x
print(x.grad) #print the gradient
print(x,y)

tensor([20.])
tensor([0.1861], requires_grad=True) tensor([3.7228], grad_fn=<MulBackward0>)
